### ISSUE TITLE
tutorial push ke git

### ISSUE THREAD

**Issue by leonalfahrezi** [bantenprov/cara-penggunaan-github#9]
[tutorial push git.txt](https://github.com/bantenprov/cara-penggunaan-github/files/10313648/tutorial.push.git.txt)

**Comment by leonalfahrezi** [comment]
bisa cek txt nya, semoga membantu bagi yang membutuhkan

**Comment by leonalfahrezi** [comment]
![tutorial git](https://user-images.githubusercontent.com/112455924/209798709-d23db2e0-7f5b-4772-b48c-fa3ad753153b.jpg)

**Comment by melgiardi** [comment]
Terimakasih, komandanku....

Pada tanggal Rab, 28 Des 2022 17.33, Leon Alfahrezi <
***@***.***> menulis:
